name: first

on: [push]

jobs:
        say_hello:
                runs-on: ubuntu-latest
                steps:
                        - uses: actions/checkout@v2
                        - name: Run make
                          run: make say-hello
